name: "Cron Build With Quarkus 1.3.x SNAPSHOT"

on:
  schedule:
    - cron: '0 3 * * *'
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11 ]
        graal: [ 19.3.1, 20.0.0 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Pull Quarkus Native Builder Image ${{ matrix.graal }}-java${{ matrix.java }}
        run: docker pull quay.io/quarkus/ubi-quarkus-native-image:${{ matrix.graal }}-java${{ matrix.java }}

      - name: Build Quarkus 1.3.x SNAPSHOT
        run: git clone --depth 1 --branch 1.3 https://github.com/quarkusio/quarkus.git && cd quarkus && echo "Current Quarkus commit:" $(git rev-parse HEAD) && mvn -B clean install -DskipTests -DskipITs

      - name: Build - JVM
        run: mvn -B clean verify -Dquarkus.version=999-SNAPSHOT

      - name: Build - Native
        run: mvn -B clean verify -Dquarkus.version=999-SNAPSHOT -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:${{ matrix.graal }}-java${{ matrix.java }}