name: Release Drafter

on:
  push:
    branches:
      - master
      - 1.1.z

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
